### ISSUE TITLE
Group Code Review

### ISSUE THREAD

**Issue by Ol-create** [NeckerFree/Capstone-Module-1#2]
@Ol-create

- You have done a very good job so far. The project is responsive to different sizes of screens and the design is similar to is the prototype.
- But the text in the next races section can be reduced in order to make it more responsive on mobile devices
- And finally, you may want to increase the height of the image in the athletic section. so as to make appropriate the text height.

@amrendrakind : 

- After clicking on the MORE button, you can hide the button from the screen.
- After clicking the on-screen menu item it should show some colour changes like the orange colour

**Comment by NeckerFree** [comment]
Changes applied in the review of the issues.
